excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://greenganjaglass.github.io
title: Ganja Life
tagline: A look at all things Mary Jane
description: Learn about the do's and don'ts of smoking, the effects of marijuana, and some helpful tips to get you higher every time!
paginate: 5